name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-cpp
  - xeus-zmq
  - CppInterOp
  - pugixml
  - cpp-argparse
  - nlohmann_json
  - python
  - xeus-python
  - ipycanvas
